"""Env + file config loader with OS-aware defaults.
Reads IAGENT_GATEWAY_URL, IAGENT_DEVICE_DATA_DIR, IAGENT_DOCKER_HOST,
IAGENT_MAX_RESTARTS, IAGENT_HEARTBEAT_S, IAGENT_AGENT_IMAGE, IAGENT_PORT_RANGE, etc.
"""
